# @format

name: Sync Repos

on:
  push:
    branches:
      - main
  # You can add more triggers, such as scheduled events
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Push to destination repository
        run: |
          git config --global user.email "taofik21.ab@gmail.com"
          git config --global user.name "Taofeek-Ib"
          git clone https://${{ env.ORG_NAME }}:${{ secrets.PAT }}@github.com/${{ env.ORG_NAME }}/dest.git
          cd dest
          git checkout -B ${{ env.DEST_BRANCH }}
          git remote add ${{ env.ORIGINAL_REPO_NAME }} https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository_owner }}/${{ env.ORIGINAL_REPO_NAME }}.git
          git remote update

          echo ".github/** merge=ours" >> .gitattributes
          git add .gitattributes
          git commit -m "Protect .github from upstream sync" || true
          git merge --no-edit --allow-unrelated-histories ${{ env.ORIGINAL_REPO_NAME }}/main
          
          git push origin ${{ env.DEST_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          ORG_NAME: tibrahim21
          DEST_BRANCH: mirror-sync
