# @format

name: Sync Repos

on:
  push:
    branches:
      - main
  # You can add more triggers, such as scheduled events
  # schedule:
  #   - cron: '0 0 * * *'
  # Optional manual run:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2  # (or @v3)

      - name: Push to destination repository
        run: |
          git config --global user.email "taofik21.ab@gmail.com"        # <-- replace
          git config --global user.name "Taofeek-Ib"                    # <-- replace

          git clone https://x-access-token:${{ secrets.PAT }}@github.com/${{ env.ORG_NAME }}/dest.git   # <-- set repo name
          cd dest                                                                                            # <-- match folder to repo

          git remote add ${{ env.ORIGINAL_REPO_NAME }} https://x-access-token:${{ secrets.PAT }}@github.com/${{ env.ORG_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git
          git remote update

          git merge --no-edit --allow-unrelated-histories ${{ env.ORIGINAL_REPO_NAME }}/main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}                               # (optional/redundant)
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}        # source repo name (auto)
          ORG_NAME: tibrahim21                                           # <-- destination owner (no spaces)
